//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W10DebloatingTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("W10DebloatingTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1439414004_sign_info {
            get {
                object obj = ResourceManager.GetObject("1439414004_sign-info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apercu {
            get {
                object obj = ResourceManager.GetObject("apercu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @echo off
        ///
        ///cls
        ///
        /// 
        ///
        ///set x86=&quot;%SYSTEMROOT%\System32\OneDriveSetup.exe&quot;
        ///
        ///set x64=&quot;%SYSTEMROOT%\SysWOW64\OneDriveSetup.exe&quot;
        ///
        /// 
        ///
        ///echo Closing OneDrive process.
        ///
        ///echo.
        ///
        ///taskkill /f /im OneDrive.exe &gt; NUL 2&gt;&amp;1
        ///
        ///ping 127.0.0.1 -n 5 &gt; NUL 2&gt;&amp;1
        ///
        /// 
        ///
        ///echo Uninstalling OneDrive.
        ///
        ///echo.
        ///
        ///if exist %x64% (
        ///
        ///%x64% /uninstall
        ///
        ///) else (
        ///
        ///%x86% /uninstall
        ///
        ///)
        ///
        ///ping 127.0.0.1 -n 5 &gt; NUL 2&gt;&amp;1
        ///
        /// 
        ///
        ///echo Removing OneDrive leftovers.
        ///
        ///echo.
        ///
        ///rd &quot;%USERPROFILE%\OneDrive&quot; /Q /S &gt; NUL 2&gt;&amp;1
        ///
        ///r [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string onedrive {
            get {
                return ResourceManager.GetString("onedrive", resourceCulture);
            }
        }
    }
}
